iem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


urlpatterns = [

    path('add_record_meta/', views.add_record_meta, name="add_record_meta"),
    path('view_profile_mt/<str:pk>/ ', views.view_profile_mt, name="view_profile_mt"),
    path('total_record_mt/', views.total_record_mt, name="total_record_mt"),
    path('delete_record_mt/<str:pk>/ ', views.delete_record_mt, name="delete_record_mt"),
    path('view_record_mt/<str:pk>/ ', views.view_record_mt, name="view_record_mt"),
    path('update_record_mt/<str:pk>/ ', views.update_record_mt, name="update_record_mt"),
    path('demographic_meta/<str:pk>/', views.demographic_meta, name="demographic_meta"),
    path('update_patient_record_meta/<str:pk>/', views.update_patient_record_meta, name="update_patient_record_meta"),
    path('update_qa_qc_iem/<str:pk>/', views.update_qa_qc_iem, name="update_qa_qc_iem"),
    path('view_qa_qc_iem/<str:pk>/', views.view_qa_qc_iem, name="view_qa_qc_iem"),

    path('total_record_mt_admin/', views.total_record_mt_admin, name="total_record_mt_admin"),
    path('export_iem/', views.export_iem_user_csv, name="export_iem"),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

irdr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('bleeding.urls')),
    path('', include('fabry.urls')),
    path('', include('glycogen.urls')),
    path('', include('iem.urls')),
    path('', include('mucopoly.urls')),
    path('', include('nmd.urls')),
    path('', include('pompe.urls')),
    path('', include('skeletal.urls')),
    path('', include('smallmolecule.urls')),
    path('', include('storage.urls')),
    path('', include('thalasemia.urls')),
    path('', include('pid.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mucopoly/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


urlpatterns = [
    path('add_record_mg/', views.add_record_mg, name="add_record_mg"),
    path('mg_demographic/<str:pk>/', views.mg_demographic, name="mg_demographic"),
    path('total_record_mg/', views.total_record_mg, name="total_record_mg"),
    path('view_record_mg/<str:pk>/ ', views.view_record_mg, name="view_record_mg"),
    path('update_record_mg/<str:pk>/ ', views.update_record_mg, name="update_record_mg"),
    path('update_patient_record_mg/<str:pk>/ ', views.update_patient_record_mg, name="update_patient_record_mg"),
    path('delete_record_mg/<str:pk>/ ', views.delete_record_mg, name="delete_record_mg"),
    path('view_profile_mg/<str:pk>/ ', views.view_profile_mg, name="view_profile_mg"),
    path('total_record_mg_admin/', views.total_record_mg_admin, name="total_record_mg_admin"),
    path('export_mucopoly/', views.export_mucopoly_user_csv, name="export_mucopoly"),
    path('mucopoly_qc/<str:pk>/', views.update_qa_qc_muco, name="update_qa_qc_muco"),
    path('view_qa_qc_muco/<str:pk>/', views.view_qa_qc_muco, name="view_qa_qc_muco"),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mucopoly/models.py
# Create your models here.

from account.models import *
from django.core.validators import FileExtensionValidator

# Create your models here.


class profile_mucopolysaccharidosis(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    qa_user = models.ForeignKey(User, null=True, blank=True,related_name='qa_user_muco', on_delete=models.CASCADE)
    register = models.ForeignKey(Register, null=True, blank=True, on_delete=models.CASCADE)
    qa_register = models.ForeignKey(Register, null=True, blank=True,related_name='qa_register_muco', on_delete=models.CASCADE)
    fb_religion_sel = [('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'),
                       ('Others', 'Others')]
    fb_caste_sel = [('Scheduled caste', 'Scheduled caste'), ('Scheduled tribe', 'Scheduled tribe'),
                    ('Others', 'Others')]
    fb_gender_sel = [('Male', 'Male'), ('Female', ' Female'), ('Transgender', 'Transgender')]
    fb_referred_by = [('General practitioner', 'General practitioner'), ('Physician', 'Physician'),
                      ('Neurologist', 'Neurologist'), ('Any others', 'Any others')]
    fb_status_sel = [('Yes', 'Yes'), ('No', 'No')]
    quality_score = [('Pass', 'Pass'), ('Fail', 'Fail')]
    quality_status_sel = [('Pending', 'Pending'), ('Resubmitted', 'Resubmitted'), ('Completed', 'Completed')]
    quality_status = models.CharField(max_length=20, blank=True, null=True, choices=quality_status_sel)
    muco_final_diagnosis = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    muco_date_of_records = models.DateField(blank=True, null=True)
    muco_date_of_clinical_exam = models.DateField(blank=True, null=True)
    muco_date_of_birth = models.DateField( null=True)
    muco_patient_name = models.CharField(max_length=100,  null=True, validators=[MaxLengthValidator(100)])
    muco_father_name = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    muco_mother_name = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    id_sel = [('Aadhar card', 'Aadhar card'), ('Driving license', 'Driving license'), ('Voter id', 'Voter id'),
              ('Rations card', 'Rations card'), ('PAN card', 'PAN card'), ('BPL card', 'BPL card'),('SECC card', 'SECC card'),('Aabha Id', 'Aabha Id') ]
    muco_paitent_id_yes_no = models.CharField(max_length=100,  null=True, choices=fb_status_sel)
    muco_paitent_id = models.CharField(max_length=100, blank=True, null=True, choices=id_sel)
    muco_patient_id_no = models.CharField(max_length=100,unique=True,blank=True,  null=True, validators=[MaxLengthValidator(100)])
    muco_patient_age = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    muco_father_mother_id = models.CharField(max_length=100, blank=True, null=True, choices=id_sel)
    muco_mother_father_id_no = models.PositiveBigIntegerField(blank=True, null=True, unique=True)
    muco_permanent_addr = models.CharField(max_length=500, blank=True, null=True, validators=[MaxLengthValidator(500)])
    muco_state = models.ForeignKey(State, null=True,  on_delete=models.CASCADE, verbose_name=' state')
    muco_district = models.ForeignKey(District, null=True, on_delete=models.CASCADE,
                                     verbose_name=' district')
    muco_city_name = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    muco_country_name = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    muco_mother_mobile_no = models.PositiveBigIntegerField( null=True, unique=True)
    muco_father_mobile_no = models.PositiveBigIntegerField(blank=True, null=True)
    muco_land_line_no = models.PositiveBigIntegerField(blank=True, null=True)
    muco_email = models.EmailField(max_length=300, blank=True, null=True)

    muco_religion = models.CharField(max_length=100, blank=True, null=True, choices=fb_religion_sel)
    muco_caste = models.CharField(max_length=100, blank=True, null=True, choices=fb_caste_sel)
    muco_referred_status = models.CharField(max_length=10, blank=True, null=True, choices=fb_status_sel)
    muco_referred_by = models.CharField(max_length=100, blank=True, null=True, choices=fb_referred_by)
    muco_referred_by_desc = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    muco_gender = models.CharField(max_length=100, blank=True, null=True, choices=fb_gender_sel)
    muco_consent_given = models.CharField(max_length=10,  null=True, choices=fb_status_sel)
    muco_consent_upload = models.FileField(upload_to='uploads/%Y/%m/%d/',  null=True, validators=[FileExtensionValidator(['pdf'])])
    muco_assent_given = models.CharField(max_length=10,  null=True, choices=fb_status_sel)
    muco_assent_upload = models.FileField(upload_to='uploads/%Y/%m/%d/', blank=True, null=True, validators=[FileExtensionValidator(['pdf'])])
    muco_hospital_name = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    muco_hospital_reg_no = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    muco_icmr_unique_no = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    muco_date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    quality_result = models.CharField(max_length=10, blank=True, null=True, choices=quality_score)
    quality_reason = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])

    uniqueId = models.CharField(null=True, blank=True, max_length=500)
    yes_no_na = [('Yes', 'Yes'), ('No', 'No'), ('Na', 'Na')]
    complete = models.CharField(max_length=10, blank=True, null=True,default='No', choices=yes_no_na)
    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        if self.uniqueId is None:
            self.uniqueId = str(uuid4())
            count1 = State.objects.count()
            count2 = 0
            count2 += count1
            super(profile_mucopolysaccharidosis, self).save(*args, **kwargs)
            self.muco_icmr_unique_no = str('Mucopolysaccharidosis/') + str(self.register.institute_code) + str('/') + str(self.pk)
            # self.slug = slugify(self.occupation)

        super(profile_mucopolysaccharidosis, self).save(*args, **kwargs)


class demographic_mucopolysaccharidosis(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    register = models.ForeignKey(Register, null=True, blank=True, on_delete=models.CASCADE)
    patient = models.ForeignKey(profile_mucopolysaccharidosis, null=True, related_name='patient_mucopoly', blank=True,
                                on_delete=models.CASCADE)

    education_status = [('Illiterate', 'Illiterate'), ('Primary', 'Primary'), ('High School', 'High School')
        , ('Secondary Level', 'Secondary Level'), ('College and above', 'College and above')]

    occupation_status = [('Employed (organised sector)', 'Employed (organised sector)'),
                         ('Employed (Unorganised sector) ', 'Employed (Unorganised sector)'),
                         ('Home maker', 'Home maker'),
                          ('Others', 'Others')]

    yes_no_sel = [('Yes', 'Yes'), ('No', 'No')]
    yes_no_sel123 = [('1', 'Yes'), ('0', 'No')]

    current_status = models.CharField(max_length=5, blank=True, null=True, choices=yes_no_sel)
    education_status_of_patient = models.CharField(max_length=50, blank=True, null=True, choices=education_status)

    occupation_of_patient = models.CharField(max_length=50, blank=True, null=True, choices=occupation_status)

    education_status_of_father = models.CharField(max_length=50, blank=True, null=True, choices=education_status)

    occupation_of_father = models.CharField(max_length=50, blank=True, null=True, choices=occupation_status)

    education_status_of_mother = models.CharField(max_length=50, blank=True, null=True, choices=education_status)

    occupation_of_mother = models.CharField(max_length=50, blank=True, null=True, choices=occupation_status)
    family_income_list = [('> 126,360', '> 126,360')
        , ('63,182 – 126,356', '63,182 – 126,356')
        , ('47,266 – 63,178', '47,266 – 63,178')
        , ('31,591 - 47,262', '31,591 - 47,262')
        , ('18,953 - 31,589', '18,953 - 31,589')
        , ('6,327 - 18,949', '6,327 - 18,949')
        , ('< 6,323', '< 6,323')]
    Age_at_Onset_of_symptoms_list = [('< 1year', '< 1year'), ('1 - 2year', '1 - 2year'), ('2 - 5year', '2 - 5year'), ('5 - 12year', '5 - 12year'), ('> 12year', '> 12year')]

    family_income = models.CharField(max_length=50, blank=True, null=True,default='No', choices=family_income_list)
    # anthropometry


    gl_anth_wght_pat = models.CharField(max_length=50,blank=True, null=True)
    gl_anth_wght_exp = models.CharField(max_length=50,blank=True, null=True)
    gl_anth_wght_per = models.CharField(max_length=50,blank=True, null=True)
    gl_anth_wght_sd = models.CharField(max_length=50,blank=True, null=True)

    gl_anth_height_pat = models.CharField(max_length=50,blank=True, null=True)
    gl_anth_height_exp = models.CharField(max_length=50,blank=True, null=True)
    gl_anth_height_per = models.CharField(max_length=50,blank=True, null=True)
    gl_anth_height_sd = models.CharField(max_length=50,blank=True, null=True)

    gl_anth_seg_pat = models.CharField(max_length=50,blank=True, null=True)
    gl_anth_seg_exp = models.CharField(max_length=50,blank=True, null=True)
    gl_anth_seg_per = models.CharField(max_length=50,blank=True, null=True)
    gl_anth_seg_sd = models.CharField(max_length=50,blank=True, null=True)

    gl_anth_ratio_pat = models.CharField(max_length=50,blank=True, null=True)

mucopoly/forms.py
from django.forms import RadioSelect, DateTimeInput
from .models import *
from django.forms import RadioSelect, DateTimeInput, NumberInput
from django.forms import FileInput
from .models import *


class ProfileMGForm(ModelForm):
    class Meta:
        model = profile_mucopolysaccharidosis
        fields = '__all__'
        widgets = {
            'muco_mother_father_id_no': TextInput(
                attrs={'placeholder': 'Please enter id number'}),
            'muco_patient_id_no': TextInput(
                attrs={'placeholder': 'Please enter patient id number'}),
            'muco_referred_by_desc': TextInput(
                attrs={'placeholder': 'Please specify'}),
            'muco_date_of_records': DateInput(attrs={'type': 'date', }),
            'muco_date_of_clinical_exam': DateInput(attrs={'type': 'date', }),
            'muco_date_of_birth': DateInput(attrs={'type': 'date', }),
            'muco_permanent_addr': Textarea(attrs={'rows': '3', 'cols': '250', }),
            'muco_consent_upload': FileInput(attrs={'accept': '.pdf'}),
            'muco_assent_upload': FileInput(attrs={'accept': '.pdf'}),
        }


class SocioDemographicDataSheetMGForm(ModelForm):
    class Meta:
        model = demographic_mucopolysaccharidosis
        fields = '__all__'
        widgets = {
            'Date_of_initiation': DateInput(attrs={'type': 'date', }),
            'date': DateInput(attrs={'type': 'date', }),
            'mg_date_created': DateInput(attrs={'type': 'date', }),
            'mg_filled_date' : DateInput(attrs={'type': 'date', }),
        }






class QAMGForm(ModelForm):
    class Meta:
        model = profile_mucopolysaccharidosis
        fields = ['qa_user','qa_register','quality_result','quality_reason']
        exclude = '__all__'
        widgets = {
            'muco_mother_father_id_no': TextInput(
                attrs={'placeholder': 'Please enter id number'}),
            'muco_patient_id_no': TextInput(
                attrs={'placeholder': 'Please enter patient id number'}),
            'muco_referred_by_desc': TextInput(
                attrs={'placeholder': 'Please specify'}),
            'muco_date_of_records': DateInput(attrs={'type': 'date', }),
            'muco_date_of_clinical_exam': DateInput(attrs={'type': 'date', }),
            'muco_date_of_birth': DateInput(attrs={'type': 'date', }),
            'muco_permanent_addr': Textarea(attrs={'rows': '3', 'cols': '250', }),
        }

mucopoly/templates/delete_record_mg.html
{%  extends 'main.html' %}
{% block content %}
{% load static %}
<html lang="en">
<head>
    <title>Inovecop</title>
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">

    <script crossorigin="anonymous"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link crossorigin="anonymous" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" rel="stylesheet">
</head>
<body>
<form action="" class="post-form" method="POST">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm">
                <h4>Are you sure you want to delete the  "{{socio}}" entry?</h4>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <a class="btn btn-warning" href="{% url 'total_record_mg' %}">Cancel</a>
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </div>
    </div>
</form>
</body>
</html>
{% endblock %}

mucopoly/templates/update_qa_qc_muco.html
{%  extends 'main.html' %} {% load static %} {% block content %} {% load extra %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
	$(document).ready(function() {
		$('#submit1').click(function(e) {
			var isValid = true;
			$('.required1').each(function() {
				if ($.trim($(this).val()) == '') {
					isValid = false;
					$(this).css({
						"border": "1px solid red",
						"background": "#FFCECE"
					});
					alert($(this).attr("name") + " " + 'field is empty')
				}
				else {
					$(this).css({
						"border": "",
						"background": ""
					});
				}
			});
			if (isValid == false)
			e.preventDefault();
			else
			alert('Thank you for submitting');
		});
	});

</script>
<style>
    input {
  border: 2px solid;
  border-radius: 4px;
  font-size: 1rem;
  margin: 0.25rem;
  min-width: 125px;
  padding: 0.5rem;
  transition: border-color 0.5s ease-out;
}
input:optional {
  border-color: gray;
}
input:required:valid {
  border-color: green;

}

input:invalid {
  border-color: red;


}
select:invalid {
  border-color: red;


}
select:required:valid {
  border-color: green;


}
</style>
<script>
	$(document).ready(function(){
	$("#id_muco_state").change(function () {
	const url = $("#personForm").attr("data-district-url");
	const DistrictId = $(this).val();  // get the selected country ID from the HTML input
	$.ajax({                       // initialize an AJAX request
	url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
	data: {
	'district_id': DistrictId       // add the town id to the GET parameters
	},
	success: function (data) {   // `data` is the return of the `load_cities` view
	console.log(data)
	$("#id_muco_district").html(data);
	}
	});
	});
	});


</script>

<script>
    /* j Query for Developmental History Records:Pre-natal Complications */
	$(document).ready(function(){
	$('#id_muco_referred_by').on('change', function(){
	var demovalue = $(this).val();
	if(demovalue == 'Any others'){
	$("#id_muco_referred_by_desc").show();
    $("label[for='referedby_others']").show();
	}
	else
	{
	$("#id_muco_referred_by_desc").hide();
    $("label[for='referedby_others']").hide();

	}
	});
	$("#id_muco_referred_by_desc").hide();
	$("label[for='referedby_others']").hide();
	});
/* j Query for Developmental History Records:Pre-natal Complications */
	$(document).ready(function(){
	$('#id_muco_consent_given').on('change', function(){
	var demovalue = $(this).val();
	if(demovalue == 'Yes'){
	$("#id_muco_consent_upload").show();
    $("label[for='consent_upload']").show();
	}
	else
	{
	$("#id_muco_consent_upload").hide();
    $("label[for='consent_upload']").hide();

	}
	});
	$("#id_muco_consent_upload").hide();
	$("label[for='consent_upload']").hide();
	});

$(document).ready(function(){
	$('#id_mt_religion').on('change', function(){
	var demovalue = $(this).val();
	if(demovalue == 'Others'){
	$("#id_muco_religion_other_specify").show();

	}
	else
	{
	$("#id_muco_religion_other_specify").hide();


	}
	});
	$("#id_muco_religion_other_specify").hide();

	});
$(document).ready(function(){
	$('#id_muco_caste').on('change', function(){
	var demovalue = $(this).val();
	if(demovalue == 'Others'){
	$("#id_muco_caste_other_specify").show();

	}
	else
	{
	$("#id_muco_caste_other_specify").hide();


	}
	});
	$("#id_muco_caste_other_specify").hide();

	});

$(document).ready(function(){
	$('#id_muco_referred_status').on('change', function(){
	var demovalue = $(this).val();
	if(demovalue == 'Yes'){
	$(".reffered_by").show();

	}
	else
	{
	$(".reffered_by").hide();


	}
	});
	$(".reffered_by").hide();

	});

	$(document).ready(function(){
	$('#id_muco_paitent_id_yes_no').on('change', function(){
	var demovalue = $(this).val();
	if(demovalue == 'Yes'){
	$(".patient_id_rule").show();

	}
	else
	{
	$(".patient_id_rule").hide();


	}
	});
	$(".patient_id_rule").hide();

	});


/* j Query for Developmental History Records:Pre-natal Complications */
	$(document).ready(function(){
	$('#id_muco_assent_given').on('change', function(){
	var demovalue = $(this).val();
	if(demovalue == 'Yes'){
	$("#id_muco_assent_upload").show();
    $("label[for='assent_upload']").show();
	}
	else
	{
	$("#id_muco_assent_upload").hide();
    $("label[for='assent_upload']").hide();

	}
	});
	$("#id_muco_assent_upload").hide();
	$("label[for='assent_upload']").hide();
	});

$(document).ready(function(){
	$("#id_muco_state").change(function () {
	const url = $("#personForm").attr("data-district-url");
	const DistrictId = $(this).val();  // get the selected country ID from the HTML input
	$.ajax({                       // initialize an AJAX request
	url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
	data: {
	'district_id': DistrictId       // add the town id to the GET parameters
	},
	success: function (data) {   // `data` is the return of the `load_cities` view function
	$("#id_muco_district").html(data);
	}
	});
	});
	});

	/* j Query for Developmental History Records:Pre-natal Complications */
	$(document).ready(function(){
	$('#id_muco_paitent_id').on('change', function(){
	var demovalue = $(this).val();
	if(demovalue == 'Aadhar card' || demovalue == 'Driving license'|| demovalue == 'Driving license'|| demovalue == 'Voter id'|| demovalue == 'Rations card'|| demovalue == 'PAN card' || demovalue == 'BPL card'){
	$("#id_muco_patient_id_no").show();

	}
	else
	{
	$("#id_muco_patient_id_no").hide();


	}
	});
	$("#id_muco_patient_id_no").hide();

	});

	/* j Query for Developmental History Records:Pre-natal Complications */
	$(document).ready(function(){
	$('#id_muco_father_mother_id').on('change', function(){
	var demovalue = $(this).val();
	if(demovalue == 'Aadhar card' || demovalue == 'Driving license'|| demovalue == 'Driving license'|| demovalue == 'Voter id'|| demovalue == 'Rations card'|| demovalue == 'PAN card' || demovalue == 'BPL card'){
	$("#id_muco_mother_father_id_no").show();

	}
	else
	{
	$("#id_muco_mother_father_id_no").hide();


	}
	});
	$("#id_muco_mother_father_id_no").hide();

	});


</script>

<style>
	ul,li {
	list-style-type: none;
	list-style-position: outside;
	margin: 4;
	padding: 0;
	}
	.required:after {
    content:" *";
    color: red;
  }
</style>
<form method="POST"  enctype="multipart/form-data" data-district-url="{% url 'load_district' %}" id="personForm" action="">

    {% csrf_token %}
    {% if form1.errors %}
    {% for field in form1 %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
        <strong>{{field.label}} --------- {{ error|escape }}</strong>
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}
    <br>

    <div class="box-body">

        <div class="box-group" id="accordion">


                    
                    <div class="box-body">
                        <div class="row ">
                            <div class="col-md-4 ">
                                <label class="col-md font-weight-bolder text-dark text-left">Quality result</label>
                                {{form2.quality_result|addclass:'form-control required1'}}
                            </div>
                            <div class="col-md-8 ">
                                <label class="col-md font-weight-bolder text-dark text-left" >Remark </label>
                                {{form2.quality_reason|addclass:'form-control required1'}}
                            </div>
                            
                        </div>
                        
                       </div>

              
        </div>
            <br>
            <center>
                <button class="btn btn-primary" type="submit" id="submit1">Submit</button>
            </center>
            <br>
        </div>
    </div>
</form>
{% endblock %}